GET http://192.168.56.101:8001/services/
content-type: application/json


### 添加 service
POST http://192.168.56.100:8001/services/
content-type: application/json

{"name":"example.service","url":"http://httpbin.org"}

### delete service
DELETE  http://192.168.56.100:8001/services/example.service

### delete route
DELETE http://192.168.56.101:8001/routes/my-route

### list routes
GET http://192.168.56.101:8001/routes/

### 在 service 上添加 route
POST http://192.168.56.101:8001/services/example.service/routes
content-type: application/json

{"paths":["/anything/[1-9][0-9]"],
"methods":["POST", "GET"], 
"name": "my-route",
"hosts":["*.test.com", "www.haha.com"], "strip_path":false}

###
POST http://192.168.56.101:8001/services/example.service/routes
content-type: application/json

{"paths":["/base64"],"strip_path":false}

### 验证 Kong 配置结果
GET http://192.168.56.100:8000/base64/aGVsbG8ga29uZw==

### ==============================================================
### ==============*************************=======================
### ==============================================================
### 查 upstream 
GET http://192.168.56.100:8001/upstreams/
content-type: application/json

### 添加 upstream
POST http://192.168.56.100:8001/upstreams/
content-type: application/json

{"name":"example.upstream"}

### 查 targets
GET http://192.168.56.100:8001/upstreams/example.upstream/targets

### 删除 targets
DELETE HTTP://192.168.56.100:8001/upstreams/example.upstream/targets/368c86c6-6567-4bbd-8d4f-4eb2fd1e6ebd



### 在 upstream 上添加 target
POST http://192.168.56.100:8001/upstreams/example.upstream/targets
content-type: application/json

{"target":"192.168.56.1:18080"}


### 在 upstream 上添加 target 2
POST http://192.168.56.100:8001/upstreams/example.upstream/targets
content-type: application/json

{"target":"192.168.56.1:18081",
 "weight": null}

### target 3
POST http://192.168.56.100:8001/upstreams/example.upstream/targets
Content-Type: application/x-www-form-urlencoded\r\n

target=backend.lite.prophet.360.cn%3A80&weight=

### 添加 service 
POST http://192.168.56.100:8001/services/
Content-Type: application/json' 

{"name":"example.service","host":"example.upstream"}


     
###
POST http://10.0.110.34:10250
content-type: application/json

{
    "cmdId": "12",
	"cmd":   "runcmds",
	"args": [
		{
			"fun": "salt_fun",
			"arg": [],
			"timeout":10
		}
	],
	"minions": ["10.0.110.34"],
	"reportType": "async",
    "reportUrl": "http://172.16.3.16:8080",
    
}


###
# POST http://10.0.120.35:22222
POST http://10.0.120.35:22222
content-type: application/json

{
	"data": [
		{
		"ip":"10.0.120.11",
		"password":"public"
		}
	]
}

###
#POST http://122.115.224.130:8015/api/collection/getdeviceInfo
POST http://122.115.224.130:8015/api/collection/getdeviceinfo
content-type: application/json

{
	"name": "test"
}